export enum SortBy {
	TITLE_ASC = "TITLE_ASC",
	TITLE_DESC = "TITLE_DESC",
	AMOUNT_BASE_CURRENCY_ASC = "AMOUNT_BASE_CURRENCY_ASC",
	AMOUNT_BASE_CURRENCY_DESC = "AMOUNT_BASE_CURRENCY_DESC",
	AMOUNT_SELECTED_CURRENCY_ASC = "AMOUNT_SELECTED_CURRENCY_ASC",
	AMOUNT_SELECTED_CURRENCY_DESC = "AMOUNT_SELECTED_CURRENCY_DESC"
}